
download
unpack
install
    # docutils-code-8215-trunk
    1) cd <archive_directory_path>
        py setup.py install
    2) test
        cd <archive_directory_path>/test3
        py alltests.py
            Unable to create process using '/bin/sh alltests.py'
        python alltests.py
            open(b'\xfc') raise UnicodeDecodeError instead of IOError!
        Traceback (most recent call last):
          ...
          File "...\docutils-code-8215-trunk\docutils\test3\test_error_reporting.py", line 224, in SafeStringTests_locale
            open(b'\xfc')
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
    3) doc
        cd <archive_directory_path>/tools
        py buildhtml.py ../
        py buildhtml.py --traceback ../docs/ref/rst
        /// Processing directory: ../docs/ref/rst
            ::: Processing: definitions.txt
            ::: Processing: directives.txt
        Traceback (most recent call last):
          ...
              File "...\docutils\parsers\rst\states.py", line 2868, in term
            classifier_node[0].rawsource = part
          File "...\docutils\nodes.py", line 569, in __getitem__
            return self.children[key]
        IndexError: list index out of range
    4) bug report
        cd ..\tools
        python quicktest.py --version
        quicktest.py (Docutils 0.15b.dev)
        http://sourceforge.net/p/docutils/bugs/
        mailto:docutils-users@lists.sourceforge.net
            ?subject=Test%20suite%20failure

